### ISSUE TITLE
errore composer su magento 2.3.2

### ISSUE THREAD

**Issue by LouNik1984** [vmasciotta/magento2-province-italiane#7]
Ho lanciato il composer require vmasciotta/magento2-province-italiane per installare ma magento da errore "Your requirements could not be resolved to an installable set of packages" (vedi screenshot).

magento: 2.3.2
server: ngnix 
php: 7.1.3

![Cattura](https://user-images.githubusercontent.com/6501073/69432272-acb40f80-0d39-11ea-85c5-fa31f00557b3.JPG)

**Comment by kvnx** [comment]
errore simile anche io su apache
![Senza titolo-1](https://user-images.githubusercontent.com/13152429/83259260-03524880-a1b8-11ea-83a6-63f724f131d8.jpg)

**Comment by vmasciotta** [comment]
issue solved in last release 1.1.1
