### ISSUE TITLE
Incompatibility with Magento 2.3.5

### ISSUE THREAD

**Issue by antonelloventurino** [vmasciotta/magento2-province-italiane#9]
Magento 2.3.5 has module-directory with version 100.3.5, so it makes impossible to install via composer

vmasciotta/magento2-province-italiane 1.1.0 requires magento/module-directory 100.0 - 100.2 -> satisfiable by magento/module-directory[100.2.10, 100.2.9, 100.2.8, 100.2.7, 100.2.6, 100.1.9, 100.2.5, 100.1.8, 100.1.7, 100.2.4, 100.2.3, 100.1.6, 100.2.2, 100.2.1, 100.1.5, 100.2.0, 100.1.4, 100.0.7, 100.1.3, 100.0.6, 100.1.2, 100.1.1, 100.1.0, 100.0.5, 100.0.4, 100.0.3, 100.0.2]

**Comment by vmasciotta** [comment]
issue solved in last release 1.1.1
